logging:
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
  level:
    root: INFO
    org.springframework: INFO
    org.springframework.data.r2dbc: DEBUG
    org.apache.http: OFF
    com.digitalinsight.apigee: DEBUG